# Generated by Django 2.2.3 on 2019-08-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilev1',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
