# Generated by Django 2.2.3 on 2019-08-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190827_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilev1',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
