# Generated by Django 2.2.3 on 2019-08-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofilev1_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilev1',
            name='phone_no',
            field=models.BigIntegerField(default=3344556677),
        ),
    ]
